-- migrate:up
CREATE SCHEMA IF NOT EXISTS jobs;

-- 1. Strict state machine representation for background processes
CREATE TYPE jobs.task_status_enum AS ENUM ('queued', 'running', 'completed', 'failed');

-- 2. Master orchestration table for Celery synchronization
CREATE TABLE jobs.background_tasks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- The native ID generated by Celery (Crucial to map both engines together)
    celery_task_id UUID UNIQUE,

    -- Telemetry classification
    task_name VARCHAR(150) NOT NULL,               -- e.g.: 'tasks.mcp_sync_drive', 'tasks.export_pdf'
    status jobs.task_status_enum NOT NULL DEFAULT 'queued',
    progress_percentage INT NOT NULL DEFAULT 0 CHECK (progress_percentage >= 0 AND progress_percentage <= 100), -- Constrained between 0 and 100

    -- Flexible metadata storage
    meta_payload JSONB,                            -- Input parameters or dynamic output results (e.g. S3 final URL)
    error_details TEXT,                            -- Custom error message if status moves to 'failed'

    -- Contextual accountability
    workspace_id UUID NOT NULL REFERENCES organizations.workspaces(id) ON DELETE CASCADE, -- Bound to the workspace
    user_id UUID REFERENCES identity.users(id) ON DELETE SET NULL, -- Track which human triggered the task

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3. High-efficiency operational indexing
CREATE INDEX idx_jobs_background_tasks_celery ON jobs.background_tasks (celery_task_id);
CREATE INDEX idx_jobs_background_tasks_workspace ON jobs.background_tasks (workspace_id);
CREATE INDEX idx_jobs_background_tasks_status ON jobs.background_tasks (status);

-- migrate:down
DROP TABLE IF EXISTS jobs.background_tasks;
DROP TYPE IF EXISTS jobs.task_status_enum;
DROP SCHEMA IF EXISTS jobs;
